// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihGGQW7XYcnDRSdYmzTIIzZs6JyIGkas',
    appId: '1:453184377334:android:7164573b5a95b12fa4f7d7',
    messagingSenderId: '453184377334',
    projectId: 'linkly-fef00',
    storageBucket: 'linkly-fef00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIqh7WJV747IFeWsevQ3Xn7u420q7rjs',
    appId: '1:453184377334:ios:3245bb81b9358e99a4f7d7',
    messagingSenderId: '453184377334',
    projectId: 'linkly-fef00',
    storageBucket: 'linkly-fef00.firebasestorage.app',
    iosBundleId: 'com.example.linkly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmImLv3PkKJXvN--Q-6HA6AJ9s18VZTic',
    appId: '1:453184377334:web:a15e86bdba0fdbbaa4f7d7',
    messagingSenderId: '453184377334',
    projectId: 'linkly-fef00',
    authDomain: 'linkly-fef00.firebaseapp.com',
    storageBucket: 'linkly-fef00.firebasestorage.app',
  );

}